# Generated by Django 5.2.5 on 2025-08-21 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('baseSalary', models.IntegerField(default=0)),
                ('departmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employee.department')),
            ],
        ),
        migrations.CreateModel(
            name='Leave_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('leaves', models.IntegerField(default=0)),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='employee.employees')),
            ],
        ),
    ]
